[workspace]
members = [
    "ch01-hello",
    "ch01-penguins",
    "ch02-complex",
    "ch02-grep-lite",
    "ch02-mandelbrot",
    "ch03-file",
    "ch04-cubesat",
    "ch05-cpu",
    "ch06-particles",
    "ch07-serde",
]