[package]
name = "ch08-resolve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.2"
rand = "0.8.5"
trust-dns = { version = "0.22.1", default-features = false }
